### PR TITLE
Optimizing BigUint and Bigint multiplication with the Toom-3 algorithm

### PR DESCRIPTION
**Pull request by kompass**
Hi !

I finally implemented the Toom-3 algorithm ! I first tried to minimize the memory allocations by allocating the `Vec<BigDigit>` myself, as was done for Toom-2, but Toom-3 needs more complex calculations, with negative numbers. So I gave up this method, to use `BigInt` directly, and it's already faster ! I also chose a better threshold for the Toom-2 algorithm.

Before any modification :
```
running 4 tests
test multiply_0        ... bench:         257 ns/iter (+/- 25)
test multiply_1        ... bench:      30,240 ns/iter (+/- 1,651)
test multiply_2        ... bench:   2,752,360 ns/iter (+/- 52,102)
test multiply_3        ... bench:  11,618,575 ns/iter (+/- 266,286)
```

With a better Toom-2 threshold (16 instead of 4) :
```
running 4 tests
test multiply_0        ... bench:         130 ns/iter (+/- 8)
test multiply_1        ... bench:      19,772 ns/iter (+/- 1,083)
test multiply_2        ... bench:   1,340,644 ns/iter (+/- 17,987)
test multiply_3        ... bench:   7,302,854 ns/iter (+/- 82,060)
```

With the Toom-3 algorithm (with a threshold of 300):
```
running 4 tests
test multiply_0        ... bench:         123 ns/iter (+/- 3)
test multiply_1        ... bench:      19,689 ns/iter (+/- 837)
test multiply_2        ... bench:   1,189,589 ns/iter (+/- 29,101)
test multiply_3        ... bench:   3,014,225 ns/iter (+/- 61,222)
```

I think this could be optimized, but it's a first step !

### CODE REVIEW

**Comment by kompass** [comment]
Hum I used a feature not available in the 1.8 again.

**Comment by kompass** [comment]
After these two optimizations :

```
running 4 tests
test multiply_0        ... bench:         103 ns/iter (+/- 4)
test multiply_1        ... bench:      15,405 ns/iter (+/- 1,377)
test multiply_2        ... bench:   1,029,812 ns/iter (+/- 29,265)
test multiply_3        ... bench:   2,634,657 ns/iter (+/- 37,420)
```
I optimized `mac_digit` too because Valgrind measured that mac3 spent 28% of its time calling mac_digit.

**Comment by cuviper** [comment]
Ping?

I'm not looking for extensive documentation, just some brief comments to explain what this code is doing.

**Comment by cuviper** [comment]
Well, I added some brief comments and made a few more performance tweaks of my own.  Let's test it!

bors r+

**Pull request merged**
