### PR TITLE
Fix code duplication error

### LINKED ISSUE #240: Failure when using num_derive on latest nightly
To reproduce, run `cargo test` on the `num/derive` subdir, you will get lots of "a type named ... has already been defined in this module".

I can reproduce with `1.15.0-nightly (0ed951993 2016-11-14)`.

This change in behaviour was probably caused by https://github.com/rust-lang/rust/pull/37614, but its actually wanted behaviour.

Basically the proc macro isn't expected anymore to output the item itself, only the impl's.

### PR DESCRIPTION
**Pull request by hauleth**
Fixes #240

### CODE REVIEW

**Comment by est31** [comment]
:+1: I confirm that this fixes #240. Thanks!

**Comment by est31** [comment]
If possible, can there be a new release of `num_derive` after this is merged?

**Comment by cuviper** [comment]
I'll publish a new `num-derive` release shortly.

**Comment by cuviper** [comment]
See `num-derive` 0.1.38.

**Pull request merged**
