### PR TITLE
Derive ToPrimitive for enums

### PR DESCRIPTION
**Pull request by PlasmaPower**
I had to double the compile fail tests, as they will bail on the first error.

I have some ideas for more complex to/from primitive derives (with inner values that implement to/from primitive), but I'll save those for a future PR.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Failure unrelated to this PR, it's instead due to https://github.com/rust-lang/rust/pull/42431

**Comment by cuviper** [comment]
That failure is also #312.

Simple enums can be cast directly to integers with `as`.  I do see the value in implementing this to support generic programming with `ToPrimitive`, but it should probably just use `as` internally.

**Comment by PlasmaPower** [comment]
@cuviper Oh I had no idea! I'll change the implementation.

**Comment by PlasmaPower** [comment]
`as` requires a value, not just a reference. We have no guarantee that the enum implements clone. It seems the current implementation is the only way.

**Comment by cuviper** [comment]
Hmm, that's awkward. Such enums should be trivially copyable.

**Comment by cuviper** [comment]
> It's illegal even if they do implement Copy, due to macro hygiene.

I don't think it's quite *that* hygienic -- at least from a quick test, deriving with `as` on a `Copy` enum seems to work for me.  But still, we can't assume `Copy`.  Maybe someday we can specialize it.

bors r+

**Comment by PlasmaPower** [comment]
@cuviper I didn't check that, but trying to use the `as` operator errors either way because the compiler doesn't know if the enum has associated values. Even though we check that, the compiler doesn't know we check that. It gives an error about the enum not being a primitive type, and suggests using `.into()`.

**Comment by cuviper** [comment]
That's ok.  What you wrote *works*, most importantly.  Thanks!

**Pull request merged**
