### PR TITLE
Check for zero denominator when parsing Ratio

### LINKED ISSUE #122: Parsing "1/0" as Ratio panics
It seems to me it should return an error. `ParseRatioError` would need to be changed into an enum. I can make a PR if this change is acceptable.

### PR DESCRIPTION
**Pull request by murarth**
Closes #122

### CODE REVIEW

**Comment by murarth** [comment]
Also, can I request a version bump after this is merged?

**Comment by cuviper** [comment]
This looks good on paper, but I'd like to run it through travis CI.  We still need to fix all that up since the move to the rust-num organization.

**Comment by cuviper** [comment]
I'm going to close and reopen to try to trigger travis CI...

**Comment by cuviper** [comment]
The failure is a known problem with num-macros, not your fault.  Looks good, thanks!

**Pull request merged**
