### PR TITLE
traits: add `to_degrees` and `to_radians` on `Float`

### LINKED ISSUE #211: Implement to_radians and to_degrees for Float
https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.to_degrees

https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.to_radians

To better mirror what's offered in the standard library, it'd be nice if these methods were available for any `Float`.

### PR DESCRIPTION
**Pull request by cuviper**
To avoid a breaking change, these have crude default implementations as
well as better implementations for `f32` and `f64` in particular.  They
don't use the inherent methods though, because `f32` didn't stabilize
those until Rust 1.7.

Fixes #211

### CODE REVIEW

**Comment by frewsxcv** [comment]
Looks great, thanks! 🎊

**Comment by cuviper** [comment]
@homu r+

**Comment by frewsxcv** [comment]
@cuviper Great! Any chance a new release could get cut?

**Comment by cuviper** [comment]
Sure - I just published num-traits-0.1.34.

**Comment by frewsxcv** [comment]
Thanks a ton! ✨

**Pull request merged**
