### PR TITLE
Improve pow speed for expensive types by multiplying references not cloned values (reopen)

### PR DESCRIPTION
**Pull request by dten**
Resubmission of https://github.com/rust-num/num/pull/152
Couldn't reopen because I broke the branch

Speed up on pow_bench

```
   test pow_bench         ... bench:   9,579,445 ns/iter (+/- 560,439)
-> test pow_bench         ... bench:   6,820,137 ns/iter (+/- 760,415)
```

### CODE REVIEW

**Comment by cuviper** [comment]
Great.  As noted in #152, we'll hold this until we're ready to make breaking changes.

**Comment by vks** [comment]
I think this could be even more efficient by using `x = x * &y` instead of `x = &x * &y`.

**Comment by dten** [comment]
@vks i suspect you're right :+1:

**Comment by cuviper** [comment]
Do you want to move this PR to the `next` branch?  That's where I'm (slowly) making breaking changes, although I'm not sure when that will get around to a release.

**Comment by dten** [comment]
That sounds the best place for it yes please

**Comment by cuviper** [comment]
Great, let's go!

bors r+

**Comment by cuviper** [comment]
Hmm, in `next` we have a default implementation of `Float::powi` using this `pow`, but `Float` doesn't have reference operators.  But I suppose we could expand those requirements...

**Comment by cuviper** [comment]
Oh, but indirect trait requirements don't propagate well.  (rust-lang/rust#20671)

I guess we can just duplicate the `powi` implementation by value for this case.  It's not *that* much code.

**Comment by cuviper** [comment]
Merged in #334, thanks!

**Pull request closed without merging**
