### PR TITLE
Add LowerHex and UpperHex formatting

### PR DESCRIPTION
**Pull request by anchovieshat**
These were mysteriously missing from BigUint.

### CODE REVIEW

**Comment by anchovieshat** [comment]
Collections were not stabilized in ```1.0.0```, causing the build failure. I could remove ```UpperHex```, or write a little extra code to make the characters uppercase.

**Comment by cuviper** [comment]
Looks good -- how about a quick test?

**Comment by anchovieshat** [comment]
What is the best way to test this? Verify that the resulting string is the same as what ```from_str_radix``` would have returned? I could check that ```UpperHex``` and ```LowerHex``` return the same value?

**Comment by cuviper** [comment]
I don't think it needs very rigorous or exhaustive testing -- just
demonstrate things that wouldn't have worked before.  Maybe try a few
`format!` calls compared with expected hex output.

**Comment by cuviper** [comment]
Great, thanks!

@homu r+ a89a2e8

**Pull request merged**
