### PR TITLE
Correct Ratio::is_negative and Ratio::is_positive

### PR DESCRIPTION
**Pull request by ollie27**
Zero is not positive or negative.

This was broken in 8be7e7bab5ffc7f998e713547b67c1a424d3b9b1.

### CODE REVIEW

**Comment by cuviper** [comment]
Ah, good catch!  Looks right -- I just want to hold this for a bit so #164 isn't disrupted...

**Comment by ollie27** [comment]
Rebased.

**Comment by cuviper** [comment]
Just noticed, is there a reason you used bitwise `&` and `|` instead of lazy-boolean `&&` and `||`?

**Comment by ollie27** [comment]
I've no idea, I've changed it to `&&` and `||` anyway.

**Comment by cuviper** [comment]
Thanks!

@homu r+ c22e3bf

**Pull request merged**
