### PR TITLE
Move functions remaining in num to num-traits

### LINKED ISSUE #102: Split num into several crates
Currently `num` mixes functionality that IMHO should be separate:

* bigints
* generic traits (`One`, `Zero`, `FromPrimitive`, `ToPrimitive`, ...)
* fractions
* complex numbers
* `range*`

The biggest offender are bigints, which are implemented very inefficiently. Real-world programs would probably rather use GMP or `ramp`.

The best plan of action would probably be creating the smaller crates and deprecating `num`?

### PR DESCRIPTION
**Pull request by vks**
Fixes #102.

### CODE REVIEW

**Comment by vks** [comment]
I will squash the commits after review.

**Comment by hauleth** [comment]
Looks good

**Comment by vks** [comment]
Squashed.

**Comment by vks** [comment]
Rebased.

**Comment by cuviper** [comment]
Thanks!

@homu r+ 3e4595e

**Pull request merged**
