### PR TITLE
Move traits into num-traits crate

### PR DESCRIPTION
**Pull request by kamalmarhubi**
This commit moves the traits module into its own crate. The new crate is
publicly imported so that downstream code will work without changes. New
code can choose to only depend on the traits crate.

Refs https://github.com/rust-num/num/issues/102

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
It should be possible for this to be a minor release.

**Comment by cuviper** [comment]
See also #164 -- you and @hauleth will have to decide how to coordinate on this.

**Comment by kamalmarhubi** [comment]
@cuviper oh I didn't realize there was already a PR open to do it.

**Comment by kamalmarhubi** [comment]
Looks like #164 is landing soon, so I'll drop this.

**Pull request closed without merging**
