### PR TITLE
Fix num-macros for nightly

### PR DESCRIPTION
**Pull request by bluss**
Now compatible with rustc 1.13.0-nightly (32571c05c 2016-09-17)

### CODE REVIEW

**Comment by bluss** [comment]
Syntax extension breaks are usually super simple things like this. For now it's sensible to just not support deriving on unions (it would be a new feature, not suitable for a fix PR).

**Comment by hauleth** [comment]
I was just working on that. But thanks 👍

**Comment by hauleth** [comment]
@homu r+

**Comment by bluss** [comment]
thanks!

**Pull request merged**
