### PR TITLE
[next] Start development on 0.2

### PR DESCRIPTION
**Pull request by cuviper**
- Drop num-macros.
- Add a workspace.
- Bump all crates to 0.2.0-git, publish=false.
- Merge the history of master without losing num-traits `no_std`.

### CODE REVIEW

**Comment by vks** [comment]
No that we can make breaking changes, we should probably reconsider how the `no_std` support was implemented for `Float`. We could for example make `Float` a subtrait of `NoStdFloat`.

**Comment by cuviper** [comment]
Yeah, that would probably better to avoid the hazard about someone implementing only the core parts.  I suggest calling it `CoreFloat` or `FloatCore`.  It doesn't need to be in *this* PR though, as I intend to leave the branch open for a while before we publish.

**Comment by vks** [comment]
Yes, there is quite a few other things we should implement in a breaking release, the generic algorithms should use the new `Num*` traits for instance.

**Comment by rubdos** [comment]
Someone already took on #281 (Serde 1.0) ? Otherwise I would wet my hands on that one.

**Pull request merged**
