### PR TITLE
macros: update string interning

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by cuviper** [comment]
However, note this warning:

```
warning: `#[derive]` for custom traits is deprecated and will be removed in v1.15. Prefer using procedural macro custom derive
  --> tests/test_macro.rs:16:28
   |
16 | #[derive(Debug, PartialEq, NumFromPrimitive)]
   |                            ^^^^^^^^^^^^^^^^
```

So this is something of a last gasp for `num-macros`, and we'll have to kill it soon.

**Comment by hauleth** [comment]
@homu r+

**Comment by cuviper** [comment]
```
failed to fetch `https://github.com/rust-lang/crates.io-index`
[16/-17] The SSL certificate is invalid
```
?!? 

@homu retry

**Comment by hauleth** [comment]
Strange

@homu retry

**Comment by cuviper** [comment]
My own testing used the same as the initial Travis build here:

```
$ rustc --version
rustc 1.15.0-nightly (2217bd771 2016-11-25)
$ cargo --version
cargo 0.16.0-nightly (b26d672 2016-11-25)
```

The failing homu builds are using:

```
$ rustc --version
rustc 1.15.0-nightly (03bdaade2 2016-11-27)
$ cargo --version
cargo 0.16.0-nightly (3568be9 2016-11-26)
```

I updated locally, and now I see the same SSL errors. :(

**Comment by cuviper** [comment]
@homu retry

**Pull request merged**
